services:
  db:
    container_name: cellim-viewer-db
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cellim_viewer
    restart: always
    networks:
      - cellim-network
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    container_name: cellim-viewer-adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    ports:
      - "8080:8080"
    restart: always
    networks:
      - cellim-network
    depends_on:
      - db

  api:
    container_name: cellim-viewer-api
    build: ./backend/
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
        - action: rebuild
          path: ./backend/pyproject.toml
    restart: always
    networks:
      - cellim-network
    volumes:
      - shared_data:/app/temp/volseg_entries
    depends_on:
      - db

  frontend:
    container_name: cellim-viewer-frontend
    build: ./frontend/
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/
        - action: rebuild
          path: ./frontend/package.json
    restart: always
    networks:
      - cellim-network

  minio:
    container_name: cellim-viewer-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - cellim-network
    volumes:
      - minio_data:/data

  volseg:
    container_name: cellim-viewer-volseg
    image: volseg:latest
    command: /bin/bash -c "cd server/cellstar_server/ && uvicorn main:app --host 0.0.0.0 --port 7000 --reload"
    ports:
      - "7000:7000"
    restart: always
    networks:
      - cellim-network
    volumes:
      - shared_data:/app/server/cellstar_server/preprocessor/temp/test_db

  nginx:
    container_name: cellim-viewer-nginx
    image: nginx:latest
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "6080:80"
      - "6443:443"
    restart: always
    networks:
      - cellim-network
    depends_on:
    - api
    - frontend
    - volseg

networks:
  cellim-network:
    driver: bridge

volumes:
  shared_data:
  db_data:
  minio_data:
