apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  instances: 1
  imageName: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.env.db }}
  storage:
    size: 10Gi
    storageClass: zfs-csi
