apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-minio-config
  namespace: {{ .Values.namespace }}
data:
  MINIO_ENDPOINT: {{ .Values.minio.env.endpoint }}
  MINIO_BROWSER_REDIRECT_URL: "https://console.minio.{{ .Release.Name }}.dyn.cloud.e-infra.cz"