apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-minio-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: "minio.{{ .Release.Name }}.dyn.cloud.e-infra.cz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-minio-service
                port:
                  number: 9000
          - path: /console
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-minio-service
                port:
                  number: 9001
