apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.secrets.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secrets.rootPassword | quote }}
