apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.secrets.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secrets.secretKey | quote }}
