apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  COOKIE_SESSION_SECRET: {{ .Values.api.secrets.cookieSessionSecret | quote }}
  JWT_SECRET_KEY: {{ .Values.api.secrets.jwtSecretKey | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.api.secrets.oidcClientSecret | quote }}
  POSTGRES_USER: overriden
  POSTGRES_PASSWORD: overriden
