apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ .Values.minio.secrets.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secrets.secretKey | quote }}
