apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
