apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-web
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
