apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: tichy3-ns
  labels:
    app: postgres
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: cellim_viewer
