apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: tichy3-ns
  labels:
    app: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  superuserSecret:
    name: demo-postgres-superuser
  storage:
    size: 10Gi
    storageClass: zfs-csi
